### PR TITLE
Update mcmod.info

### PR DESCRIPTION
**Pull request by Omgise**
Fix the issue of § turning into � in mcmod.info.

### CODE REVIEW

**Comment by kotmatross28729** [comment]
Strange, it displays fine for me:

23131Снимок

64654Снимок


Your current change is simply to remove text coloring, can you explain more specifically?

**Comment by Omgise** [comment]
This is a screenshot of `itemphysic-1.2.7.jar `in the game and a screenshot of mcmod.info
image
image

**Comment by Omgise** [comment]
This looks quite strange 🤔

**Comment by kotmatross28729** [comment]
What about Et Futurum Requiem? It does exactly the same

**Comment by Omgise** [comment]
Et Futurum Requiem has removed text coloring

**Comment by Omgise** [comment]
Oh, he didn't delete it, I misread it. Maybe it's a problem with your build script?

**Comment by kotmatross28729** [comment]
I don’t think so, I would see the same thing, but it works for me

As far as I understand, it is displayed normally in EFR?

**Comment by Omgise** [comment]
I understand now, he used the color symbols directly `§`
image

**Comment by Omgise** [comment]
And you are using `\u00A7c` , so there was a problem

**Comment by kotmatross28729** [comment]
`\u00A7` and `§` are the same thing, and they are processed the same by the game (should)

**Comment by Omgise** [comment]
> I don’t think so, I would see the same thing, but it works for me我不这么认为，我会看到同样的事情，但它对我有效
> 
> As far as I understand, it is displayed normally in EFR?据我了解，EFR中正常显示吗？

Yes, it displays normally

**Comment by Omgise** [comment]
> `\u00A7` and `§` are the same thing, and they are processed the same by the game (should)

idk 🤔

**Comment by kotmatross28729** [comment]
Very strange, EFR does not work for me:

**Comment by kotmatross28729** [comment]
And when I changed `\u00A7` to `§` in ItemPhysic it also stopped working for me

**Comment by Omgise** [comment]
image

**Comment by kotmatross28729** [comment]
Okay then try this, I'm wondering if it will work for you:

[itemphysic.zip](https://github.com/user-attachments/files/17879721/itemphysic.zip)

**Comment by Omgise** [comment]
What a strange display bug

**Comment by Omgise** [comment]
image

**Comment by kotmatross28729** [comment]
This is really something strange:

When compiling a mod with `\u00A7`, in mcmod.info it is replaced with `§`, and it works in the game (at least for me)

When compiling a mod with `§`, it remains in mcmod.info as well, but it doesn’t work for me.

That is, we have 2 identical mcmod.info, in which this character is represented the same way, but the result depends on how it was encoded when compiling, HOW DOES THIS WORK??

**Comment by Omgise** [comment]
I am also just a beginner in Java, and I don't understand either

**Comment by kotmatross28729** [comment]
I'm not so much a beginner anymore, but I also don't understand anything

**Comment by Omgise** [comment]
I found that the display of the enderlicious mod is normal. Maybe it modifies the text color through code?
image
image

**Comment by kotmatross28729** [comment]
Yes, most likely.

 ItemPhysic did this too, but I deleted it, I don’t remember why

**Comment by Omgise** [comment]
EFR may have the same reason

**Comment by Omgise** [comment]
@Roadhog360 Can you help me?

**Comment by kotmatross28729** [comment]
@Omgise , try this:

[itemphysic.zip](https://github.com/user-attachments/files/17879834/itemphysic.zip)

**Comment by Omgise** [comment]
Good job! Thank you for your help, it is displaying normally ❤️

**Comment by Omgise** [comment]
image

**Pull request closed without merging**
